In [1]:
import pandas as pd
import sys
from pathlib import Path


ROOT_PROJECT = Path.cwd().parent
DATA_ROUTE = ROOT_PROJECT / 'models' / 'kmeans' / 'results'
SRC = ROOT_PROJECT / 'src'

if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from utils.analyze import(
    get_sizes_groups,
    describe_clusters,
    describe_clusters_median
)

file_path = DATA_ROUTE / "labeled_frame.csv"

df = pd.read_csv(file_path)

In [2]:
sizes_drains = get_sizes_groups(df)
sizes_drains

   labels  tamano  porcentajes
0       0   17325     0.532127
1       1    1344     0.041280
2       2    8093     0.248572
3       3    5796     0.178021

In [3]:
X_describe_clusters = describe_clusters(df)
X_describe_clusters

labels                              0             1         2            3
conteo_requests                  1.00  1.600600e+02      2.48         4.91
times_timestamp                  1.00  1.600600e+02      2.48         4.91
request_amount                   1.00  1.600600e+02      2.48         4.91
routes_visited                   1.00  1.600600e+02      2.48         4.91
activity_window_ms               0.01  1.896498e+08  15788.77  53727824.42
mean_time_between_requests_ms    0.01  3.119851e+06  11229.30  20605972.49
median_time_between_requests_ms  0.01  1.215226e+06  10313.69  17904741.94
is_one_shot                      1.00  0.000000e+00      0.00         0.00

In [4]:
X_describe_clusters.to_json()

'{"0":{"conteo_requests":1.0,"times_timestamp":1.0,"request_amount":1.0,"routes_visited":1.0,"activity_window_ms":0.01,"mean_time_between_requests_ms":0.01,"median_time_between_requests_ms":0.01,"is_one_shot":1.0},"1":{"conteo_requests":160.06,"times_timestamp":160.06,"request_amount":160.06,"routes_visited":160.06,"activity_window_ms":189649757.8700000048,"mean_time_between_requests_ms":3119851.4300000002,"median_time_between_requests_ms":1215225.76,"is_one_shot":0.0},"2":{"conteo_requests":2.48,"times_timestamp":2.48,"request_amount":2.48,"routes_visited":2.48,"activity_window_ms":15788.77,"mean_time_between_requests_ms":11229.3,"median_time_between_requests_ms":10313.69,"is_one_shot":0.0},"3":{"conteo_requests":4.91,"times_timestamp":4.91,"request_amount":4.91,"routes_visited":4.91,"activity_window_ms":53727824.4200000018,"mean_time_between_requests_ms":20605972.4899999984,"median_time_between_requests_ms":17904741.9400000013,"is_one_shot":0.0}}'

In [5]:
X_describe_median = describe_clusters_median(df)
X_describe_median

labels                           0          1     2         3
conteo_requests                  1         71     2         4
times_timestamp                  1         71     2         4
request_amount                   1         71     2         4
routes_visited                   1         71     2         4
activity_window_ms               0  212806072  1046  29630617
mean_time_between_requests_ms    0    2745349   995  11039436
median_time_between_requests_ms  0    1205206   872   6495223
is_one_shot                      1          0     0         0

In [6]:
X_describe_median.to_json()

'{"0":{"conteo_requests":1,"times_timestamp":1,"request_amount":1,"routes_visited":1,"activity_window_ms":0,"mean_time_between_requests_ms":0,"median_time_between_requests_ms":0,"is_one_shot":1},"1":{"conteo_requests":71,"times_timestamp":71,"request_amount":71,"routes_visited":71,"activity_window_ms":212806072,"mean_time_between_requests_ms":2745349,"median_time_between_requests_ms":1205206,"is_one_shot":0},"2":{"conteo_requests":2,"times_timestamp":2,"request_amount":2,"routes_visited":2,"activity_window_ms":1046,"mean_time_between_requests_ms":995,"median_time_between_requests_ms":872,"is_one_shot":0},"3":{"conteo_requests":4,"times_timestamp":4,"request_amount":4,"routes_visited":4,"activity_window_ms":29630617,"mean_time_between_requests_ms":11039436,"median_time_between_requests_ms":6495223,"is_one_shot":0}}'