In [ ]:
import pandas as pd
import numpy as np 
import os
import json
import matplotlib.pyplot as plt
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
DATA_SOURCE = PROJECT_ROOT / 'Data'
DAY_LOGS = DATA_SOURCE / 'vercel_logs_runtime' / 'data_today.csv'

route_all_drains = '/Users/marcoantoniogarciamartinez/Documents/Python Local/Proyectos/PIDA-copy/Data/db_supabase/data_actualizada_drain_logs_vercel.csv'


data = pd.read_csv(DAY_LOGS)

In [2]:
all_drains = pd.read_parquet(route_all_drains)
all_drains.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345352 entries, 0 to 345351
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   path              345352 non-null  object
 1   message           64314 non-null   object
 2   requestId         345352 non-null  object
 3   timestamp         345352 non-null  int64
 4   proxy.path        345352 non-null  object
 5   proxy.method      345352 non-null  object
 6   proxy.clientIp    345352 non-null  object
 7   proxy.timestamp   345352 non-null  int64
 8   proxy.userAgent   345315 non-null  object
 9   proxy.statusCode  345133 non-null  float64
 10  ja4Digest         281038 non-null  object
 11  proxy.referer     131707 non-null  object
dtypes: float64(1), int64(2), object(9)
memory usage: 31.6+ MB

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10302 entries, 0 to 10301
Data columns (total 30 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TimeUTC             10302 non-null  object
 1   timestampInMs       10302 non-null  int64
 2   requestPath         10302 non-null  object
 3   requestMethod       10302 non-null  object
 4   requestQueryString  1778 non-null   object
 5   responseStatusCode  10301 non-null  float64
 6   requestId           10302 non-null  object
 7   requestUserAgent    10301 non-null  object
 8   level               15 non-null     object
 9   environment         10302 non-null  object
 10  branch              10281 non-null  object
 11  vercelCache         10281 non-null  object
 12  type                10289 non-null  object
 13  function            10302 non-null  object
 14  host                10302 non-null  object
 15  deploymentDomain    10281 non-null  object
 16  deploymentId        10302 non-null  object
 17  durationMs          10247 non-null  float64
 18  region              10274 non-null  object
 19  maxMemoryUsed       5623 non-null   float64
 20  memorySize          5623 non-null   float64
 21  message             15 non-null     object
 22  projectId           10302 non-null  object
 23  traceId             0 non-null      float64
 24  sessionId           0 non-null      float64
 25  invocationId        5623 non-null   object
 26  instanceId          5623 non-null   object
 27  concurrency         5623 non-null   float64
 28  workflowRunId       0 non-null      float64
 29  workflowStepId      0 non-null      float64
dtypes: float64(9), int64(1), object(20)
memory usage: 2.4+ MB

In [22]:
userAgents = (
    data
    .groupby('requestUserAgent')
    .agg(
        conteo = ('requestUserAgent', 'count'),
        duracion = ('durationMs', 'sum')
    )
    ).reset_index()

In [23]:
userAgents

                                      requestUserAgent  conteo  duracion
0             Chrome Privacy Preserving Prefetch Proxy       5     128.0
1    CriteoBot/0.1 (+https://www.criteo.com/criteo-...      92    8169.0
2    DuckDuckGo/5 (com.duckduckgo.mobile.android; A...       1      11.0
3    IAS Crawler (ias_crawler; http://integralads.c...      87    2425.0
4                                 Mediapartners-Google      74    8140.0
..                                                 ...     ...       ...
485  ias-or/3.3 (former https://www.admantx.com + h...       2     343.0
486  ias-va/3.3 (former https://www.admantx.com + h...      57    1637.0
487  meta-externalagent/1.1 (+https://developers.fa...     141   60804.0
488  meta-webindexer/1.1 (+https://developers.faceb...      40   21852.0
489                                 peer39_crawler/1.0       9     103.0

[490 rows x 3 columns]

In [24]:
userAgents.sort_values('conteo', ascending = False).head(40)

                                      requestUserAgent  conteo  duracion
28   Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...    1850  553496.0
401  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...    1805  547618.0
479  Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...    1077  464372.0
474  Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...    1060  468363.0
35   Mozilla/5.0 (Linux; Android 5.0) AppleWebKit/5...     540  256216.0
477  Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...     455   40265.0
39   Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Bu...     325  147036.0
108  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...     192  100358.0
437  Mozilla/5.0 (compatible; proximic; +https://ww...     152    5892.0
470  Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Ma...     144   94760.0
487  meta-externalagent/1.1 (+https://developers.fa...     141   60804.0
472  Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...      94   62591.0
1    CriteoBot/0.1 (+https://www.criteo.com/criteo-...      92    8169.0
417  Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...      89   28036.0
432  Mozilla/5.0 (compatible; Bytespider; spider-fe...      89    4627.0
3    IAS Crawler (ias_crawler; http://integralads.c...      87    2425.0
453  Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like M...      82   21448.0
27   Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...      74   19257.0
4                                 Mediapartners-Google      74    8140.0
433  Mozilla/5.0 (compatible; DotBot/1.2; +https://...      71   55438.0
26   Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...      60   16374.0
486  ias-va/3.3 (former https://www.admantx.com + h...      57    1637.0
376  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...      53   13034.0
402  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...      50   17168.0
403  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...      47    3906.0
45   Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/...      40   24669.0
488  meta-webindexer/1.1 (+https://developers.faceb...      40   21852.0
125  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...      31   12794.0
124  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...      27    3703.0
399  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...      26    9929.0
465  Mozilla/5.0 (iPhone; CPU iPhone OS 26_5_0 like...      25    4815.0
388  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...      23    5501.0
436  Mozilla/5.0 (compatible; TTD-Content; +https:/...      22     965.0
434  Mozilla/5.0 (compatible; Googlebot/2.1; +http:...      21    3468.0
459  Mozilla/5.0 (iPhone; CPU iPhone OS 26_4_1 like...      19    4468.0
107  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...      17    1721.0
393  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...      16    4999.0
120  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...      15    8561.0
464  Mozilla/5.0 (iPhone; CPU iPhone OS 26_5_0 like...      15    2192.0
117  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...      15   14548.0

In [27]:
userAgents['userNorm'] = userAgents['requestUserAgent'].str.lower()

userAgents[userAgents['userNorm'].str.contains('uninet')]

Empty DataFrame
Columns: [requestUserAgent, conteo, duracion, userNorm]
Index: []